# -*- coding: utf-8 -*-
"""外部主程序用：统一从 UTF-8 源码导入，勿用 QMT 部署目录下的 GBK 副本。"""
from qmt_builtin.src.ant_rules_io import (  # noqa: F401
    RESULTS_FLUSH_INTERVAL_SEC,
    RESULTS_PATH,
    RESULTS_VERSION,
    RULES_ARMED_PATH,
    RULES_RELOAD_INTERVAL_SEC,
    RULES_VERSION,
    append_stock_event,
    collect_subscribe_codes,
    default_paths,
    empty_results,
    extract_tick_high_low,
    extract_tick_open,
    extract_tick_price,
    load_json,
    load_results_prices,
    load_account_positions_snapshot,
    load_orders_snapshot,
    load_broker_orders_snapshot,
    load_elastic_states_snapshot,
    load_rules_armed,
    normalize_armed_task,
    normalize_watch_codes,
    prune_results_stocks,
    rules_file_signature,
    save_json_atomic,
    update_price_snapshot,
)
